export const Livingdata = [
  { title: "가구/인테리어", content: "거실가구" },
  { content: "주방가구" },
  { content: "수납가구" },
  { content: "침실가구" },
  { content: "사무실가구" },
  { content: "침구류" },
  { content: "홈데코" },
  { title: "생활/건강", content: "청소/욕실" },
  { content: "마스크" },
  { content: "생활마카" },
  { content: "연필/샤프" },
  { title: "주방", content: "식기류" },
  { content: "보관용기" },
  { content: "잔/컵" },
  { content: "조리기구" },
  { content: "물병/텀블러" },
  { content: "주방잡화" },
  { content: "드립/포트" },
  { title: "디지털/가전", content: "생활가전" },
  { content: "주방가전" },
  { title: "수납", content: "박스/보관" },
  { content: "소품수납" },
  { content: "여행/캠핑" },
  { content: "텐트" },
  { content: "의자" },
  { content: "매트/침대" },
  { content: "테이블" },
  { content: "취사용품" },
  { title: "하비", content: "DIY/KIT" },
  { content: "아트/북" },
  { content: "잉크랩" },
  { content: "원데이클래스" },
  { title: "모나르떼", content: "모나르떼" },
];
