export const Monamipetdata = [
  { main_title: "DOG", title: "사료", content: "건식사료" },
  { content: "습식사료" },
  { content: "퍼피" },
  { content: "시니어" },
  { content: "간식" },
  { content: "동결건조간식" },
  { content: "껌" },
  { content: "저키/트릿" },
  { content: "비스킷/소세지" },
  { content: "캔/파우치" },
  { content: "수제간식/영양제" },
  { title: "용품", content: "홈리빙" },
  { content: "배변" },
  { content: "그루밍" },
  { content: "외출" },
  { content: "놀이/훈련" },
  { content: "패션" },
  { title: "프리미엄 식품관", content: "K9" },
  { content: "맥아담스" },
  { content: "카나간" },
  { content: "헤일로" },
  { content: "오리젠" },
  { content: "윔지스" },
  { main_title: "CAT", title: "사료", content: "건식사료" },
  { content: "습식사료" },
  { content: "키튼" },
  { content: "어덜트" },
  { content: "시니어" },
  { content: "시니어" },
  { title: "간식", content: "동결건조간식" },
  { content: "저키/트릿" },
  { content: "비스킷/소시지" },
  { content: "캔/파우치" },
  { content: "수제간식/영양제" },
  { content: "캣닢/캣그라스" },
  { title: "용품", content: "홈리빙" },
  { content: "배변" },
  { content: "그루밍" },
  { content: "외출" },
  { content: "놀이/훈련" },
  { content: "패션" },
  { title: "프리미엄 식품관", content: "K9(필라인)" },
  { content: "RAWZ" },
  { content: "아카나" },
  { content: "헤일로" },
  { content: "오리젠" },
  { content: "게더" },
];
