export const Stationerydata = [
  { title: "프리미엄 펜", content: "153프리미엄" },
  { content: "데스크펜/스마트펜" },
  { content: "파카" },
  { content: "카렌다쉬" },
  { content: "카웨코" },
  { content: "매뉴스크립트" },
  { title: "펜/펜슬", content: "볼펜" },
  { content: "수성펜/사인펜" },
  { content: "연필/샤프" },
  { content: "형광펜" },
  { title: "마카", content: "네임펜/유성매직" },
  { content: "생활/보드마카" },
  { content: "패브릭/세라믹마카" },
  { title: "컬러링/브러쉬", content: "컬러링펜" },
  { content: "브러쉬펜" },
  { content: "미술용품" },
  { content: "미술용품" },
  { title: "디자인 문구", content: "몰스킨" },
  { content: "다이어리/노트" },
  { content: "카드/봉투" },
  { content: "파우치" },
  { content: "풀/스티커/테이프" },
  { content: "스탬프" },
  { content: "데스크용품" },
  { content: "모나미 MD상품" },
];
