export const Storypickdata = [
  { title: "Stationery", content: "필기" },
  { content: "취미" },
  { title: "MonamiPet", content: "Puppy's Diary" },
  { content: "훈련" },
  { content: "노하우" },
  { content: "일상" },
  { content: "푸드" },
  { title: "Living&amp;Life", content: "모나르떼" },
  { content: "인테리어" },
  { content: "DIY" },
  { content: "Gift" },
  { title: "Gift", content: "특별한 선물" },
  { content: "교육" },
  { content: "미술" },
];
